repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.2
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict # prevent committing files with merge conflicts
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args: [-L, "nd,hist", "--skip", "*.ipynb"]
